export const LEADERBOARD_PAGES = {
    COMPETITION: "competition",
    COMPETITION_HISTORY: "competition-history",
    TRADERS: "traders",
    TRADERS_HISTORY: "traders-history",
    POOLS: "pools",
    POOLS_HISTORY: "pools-history",
};

export const LEADERBOARD_PAGES_ORDER = [
    LEADERBOARD_PAGES.COMPETITION,
    LEADERBOARD_PAGES.COMPETITION_HISTORY,
    LEADERBOARD_PAGES.TRADERS,
    LEADERBOARD_PAGES.TRADERS_HISTORY,
    LEADERBOARD_PAGES.POOLS,
    LEADERBOARD_PAGES.POOLS_HISTORY,
];

export const MIN_COLLATERAL_USD_IN_LEADERBOARD = 100; 